files:
  - source: /*.json
    translation: /translation/%two_letters_code%/%original_file_name%
  - source: /*.xml
    ignore:
      - /Example.xml
    translation: /project/%three_letters_code%/%original_file_name%
    translate_content: 0
    translate_attributes: 0
    update_option: update_without_changes
    export_languages:
      - uk
      - spa
