files:
  - source: /*.json
    translation: /translation/%two_letters_code%/%original_file_name%
    update_option: update_without_changes
     export_languages:
      - uk
      - spa
  - source: '*.xml'
    ignore:
      - Example.xml
    translation: /project/%three_letters_code%/%original_file_name%
    language_mapping:
      ukr:
        two_letters_code: ua
      spa:
        two_letters_code: sp
