files:
  - source: /*.json
    translation: /translation/%two_letters_code%/%original_file_name%
  - source: /*.xml
    translation: /project/%three_letters_code%/%original_file_name%
    translate_content: 0
    translate_attributes: 0
