files:
  - source: /*.json
    translation: /translation/%two_letters_code%/%original_file_name%
  - source: '*.xml'
    ignore:
      - Example.xml
    translation: /project/%three_letters_code%/%original_file_name%
